### ISSUE TITLE
Installation 403

### ISSUE THREAD

**Issue by ghost** [SmalsResearch/NominatimWrapper#5]
I'm trying to install an instance of this project, when doing a full download for the planet with this config:

```
version: "3"
services:
  nominatim:
    container_name: nominatim
    image: mediagis/nominatim:4.2
    restart: always
    ports:
        - "8080:8080"
    environment:
            # see https://github.com/mediagis/nominatim-docker/tree/master/3.7#configuration for more options
#          PBF_URL: https://download.geofabrik.de/europe/monaco-latest.osm.pbf
#          REPLICATION_URL: https://download.geofabrik.de/europe/monaco-updates/
         PBF_URL: https://ftp5.gwdg.de/pub/misc/openstreetmap/planet.openstreetmap.org/pbf/planet-latest.osm.pbf
         REPLICATION_URL: https://ftp5.gwdg.de/pub/misc/openstreetmap/planet.openstreetmap.org/replication/day/
         NOMINATIM_PASSWORD: very_secure_password_1234
         IMPORT_WIKIPEDIA: "true"
         IMPORT_STYLE: address
    volumes:
         - nominatim-data:/var/lib/postgresql/12/main
    shm_size: 1gb


  photon:
    build:
        context: .
        dockerfile: Docker/Dockerfile_photon
        args:
         - photon_data=Docker/photon.tar.gz
        # network: host
    ports:
      - "2322:2322"

  libpostal:
    build:
        context: .
        dockerfile: Docker/Dockerfile_libpostal
        # network: host
    ports:
            - "7000:7000"
    environment:
      - NB_LPOST_WORKERS:1

  wrapper:
    build:
        context: .
        dockerfile: Docker/Dockerfile_wrapper
        # network: host
    ports:
      - "5000:5000"
    environment:
      - NB_WORKERS=8
      - PHOTON_HOST=photon:2322
      - LPOST_HOST=libpostal:7000
      - OSM_HOST=nominatim:8080
      - LOG_LEVEL=low
      - TIMING=no
      - FASTMODE=yes
      - HTTPS=yes
volumes:
    nominatim-data:

```

After having done `./full_build.sh` which succeeds I ran `docker-compose -f docker-compose-full.yml up` I am getting these 403's:

```
100   153  100   153    0     0   1425      0 --:--:-- --:--:-- --:--:--  1429
nominatim    | curl: (22) The requested URL returned error: 403
nominatim    | + tailpid=0
nominatim    | + replicationpid=0
nominatim    | + trap stopServices SIGTERM TERM INT
nominatim    | + /app/config.sh
nominatim    | + id nominatim
nominatim    | user nominatim already exists
nominatim    | + echo 'user nominatim already exists'
nominatim    | + IMPORT_FINISHED=/var/lib/postgresql/14/main/import-finished
nominatim    | + '[' '!' -f /var/lib/postgresql/14/main/import-finished ']'
nominatim    | + /app/init.sh
nominatim    | + OSMFILE=/nominatim/data.osm.pbf
nominatim    | + CURL=("curl" "-L" "-A" "${USER_AGENT}" "--fail-with-body")
nominatim    | + '[' true = true ']'
nominatim    | Downloading Wikipedia importance dump
nominatim    | + echo 'Downloading Wikipedia importance dump'
nominatim    | + curl -L -A mediagis/nominatim-docker:4.2.3 --fail-with-body https://nominatim.org/data/wikimedia-importance.sql.gz -o /nominatim/wikimedia-importance.sql.gz
nominatim    |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
nominatim    |                                  Dload  Upload   Total   Spent    Left  Speed
100   153  100   153    0     0   1164      0 --:--:-- --:--:-- --:--:--  1167
nominatim    | curl: (22) The requested URL returned error: 403
nominatim    | + tailpid=0
nominatim    | + replicationpid=0
nominatim    | + trap stopServices SIGTERM TERM INT
nominatim    | + /app/config.sh
nominatim    | + id nominatim
nominatim    | + echo 'user nominatim already exists'
nominatim    | + IMPORT_FINISHED=/var/lib/postgresql/14/main/import-finished
nominatim    | + '[' '!' -f /var/lib/postgresql/14/main/import-finished ']'
nominatim    | + /app/init.sh
nominatim    | user nominatim already exists
nominatim    | + OSMFILE=/nominatim/data.osm.pbf
nominatim    | + CURL=("curl" "-L" "-A" "${USER_AGENT}" "--fail-with-body")
nominatim    | Downloading Wikipedia importance dump
nominatim    | + '[' true = true ']'
nominatim    | + echo 'Downloading Wikipedia importance dump'
nominatim    | + curl -L -A mediagis/nominatim-docker:4.2.3 --fail-with-body https://nominatim.org/data/wikimedia-importance.sql.gz -o /nominatim/wikimedia-importance.sql.gz
nominatim    |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
nominatim    |                                  Dload  Upload   Total   Spent    Left  Speed
100   153  100   153    0     0   1409      0 --:--:-- --:--:-- --:--:--  1416
nominatim    | curl: (22) The requested URL returned error: 403

```

Is this normal?
